packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@react-pdf/renderer": ^4.5.1
  "@types/node": ^24
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  react: ^19.2.8
  react-dom: ^19.2.8
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
